package ExceptionHandeling;

public class FinallyBlock {

	
	// 
	public static void main(String[] args) 
	{
	
		
		try
		{
			System.out.println("Try block");
			int num=121/0;  
			System.out.println(num);
			
		}
		catch(ArrayIndexOutOfBoundsException e) // change it to array index out of bound exception --ArrayIndexOutOfBoundsException
		{
			System.out.println("Number should not be divided by zero");
		}
		finally
		{
			System.out.println("This is finally block");
		}
		
		
		

	}

}
